FROM node:14 as node

WORKDIR /app

RUN git clone -b b%%TAG%% -o upstream https://github.com/TerraMA2/satalertas-client.git . && \
    npm install

COPY config/environment.prod.ts /app/src/environments/environment.prod.ts
COPY config/environment.ts /app/src/environments/environment.ts

RUN npx ng build --prod --base-href %%BASE_PATH%%alerta/ --deploy-url %%BASE_PATH%%alerta/

FROM nginx

COPY --from=node /app/dist/satalertas-client/ /usr/share/nginx/html%%BASE_PATH%%alerta/
COPY config/nginx.conf /etc/nginx/conf.d/default.conf