version: "3.3"

networks:
  net:
    external:
      name: "${COMPOSE_PROJECT_NAME}_net"

services:

 satalertas_server:
  image: ${TERRAMA2_DOCKER_REGISTRY}/${COMPOSE_PROJECT_NAME}-satalertas-server:${TAG}
  restart: "always"
  environment:
      - NODE_ENV=production
  volumes:
      - ./server/config.json:/app/config/config.json
      - ./server/geoserver-conf/config.json:/app/geoserver-conf/config.json
      - "satalertas_documents_vol:/app/documentos"
      - "satalertas_vol:/data"
  ports:
      - "0.0.0.0:${SERVER_PORT}:3200"
  networks:
      - net

 satalertas_client:
  image: ${TERRAMA2_DOCKER_REGISTRY}/${COMPOSE_PROJECT_NAME}-satalertas-client:${TAG}
  restart: "always"
  volumes:
      - "satalertas_vol:/data"
  ports:
      - "0.0.0.0:${CLIENT_PORT}:80"
  networks:
      - net

 quickchart:
    image: ianw/quickchart
    restart: "always"
    ports:
      - "0.0.0.0:${QUICKCHART_PORT}:3400"
    networks:
      - net

volumes:
  satalertas_documents_vol:
  satalertas_vol: