FROM node:14-alpine

WORKDIR /app

ENV NODE_ENV=production

RUN apk add gdal zip git bash && \
    git clone -b b%%VERSION%% -o upstream https://github.com/TerraMA2/satalertas-server.git . && \
    npm ci --only=production --silent

ENTRYPOINT ["npm", "run", "prod"]
