FROM node:12-alpine

WORKDIR /app

RUN apt-get update && \
    apt-get install -y gdal-bin zip && \
    git clone -b b%%TAG%% -o upstream https://github.com/TerraMA2/satalertas-server.git . && \
    npm install --production

ENV NODE_ENV=production

EXPOSE 3200

ENTRYPOINT ["npm", "run", "prod"]