FROM node:14-alpine

WORKDIR /app

RUN apk add gdal zip git bash && \
    git clone -b b%%VERSION%% -o upstream https://github.com/TerraMA2/satalertas-server.git . && \
    npm install --production

ENV NODE_ENV=production

EXPOSE 3200

ENTRYPOINT ["npm", "run", "prod"]
