pipeline {
    agent any
    parameters {
        choice(name: 'VERSION', choices: ['2.0.0-dev', '1.0.1'], description: 'Satalertas branch')
        string(name: 'COMPOSE_PROJECT_NAME', defaultValue: 'develop', description: 'Compose project name (used on docker-compose "-p" parameter)')
        string(name: 'PROJECT_ID', defaultValue: 'mpmt', description: 'Project ID')
        string(name: 'BASE_URL', defaultValue: 'http://www.terrama2.dpi.inpe.br', description: 'Server url')
        string(name: 'BASE_PATH', defaultValue: '/develop/', description: 'Server URL base path')
        booleanParam(name: 'DEPLOY', defaultValue: true, description: 'Should deploy after build?')
    }
    stages {
        stage('Build') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com/', 'dockerhub') {
                        echo 'Creating .env file..'
                        sh './scripts/create-env.sh $VERSION $COMPOSE_PROJECT_NAME $PROJECT_ID $BASE_PATH $BASE_URL'
                        echo 'Generating config files..'
                        sh './scripts/generate-config.sh'
                        echo 'Building images..'
                        def clientImage = docker.build("terrama2/$COMPOSE_PROJECT_NAME-satalertas-client:$VERSION", './client')
                        def serverImage = docker.build("terrama2/$COMPOSE_PROJECT_NAME-satalertas-server:$VERSION", './server')
                        echo 'Pushing images to the registry..'
                        clientImage.push();
                        serverImage.push();
                    }
                }
            }
        }
        stage('Deploy') {
            when {
                expression {
                    params.DEPLOY
                }
            }
            agent {
                docker {
                    image 'python:3.8'
                    args: '-u root'
                }
            }
            steps {
                sh 'pip install requests && python3 portainer/update-stack.py $COMPOSE_PROJECT_NAME $VERSION $BASE_URL'
            }
        }
    }
}

