version: "3.8"

services:

  server:
    image: ${TERRAMA2_DOCKER_REGISTRY}/${COMPOSE_PROJECT_NAME}-satalertas-server:${VERSION}
    restart: "always"
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 2
        condition: on-failure
    hostname: satalertas_server
    environment:
      - NODE_ENV=production
    volumes:
      - "satalertas_documents_vol:/app/documentos"
      - "satalertas_vol:/data"
    ports:
      - "${SERVER_PORT}:3200"
    configs:
      - source: ${COMPOSE_PROJECT_NAME}_satalertas_server_config
        target: /app/config/config.json
      - source: ${COMPOSE_PROJECT_NAME}_satalertas_geoserver_config
        target: /app/geoserver-conf/config.json
    networks:
      - backend
      - frontend

  client:
    image: ${TERRAMA2_DOCKER_REGISTRY}/${COMPOSE_PROJECT_NAME}-satalertas-client:${VERSION}
    restart: "always"
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 2
        condition: on-failure
    environment:
      - PRODUCTION=true
      - PROJECT_ID=mpmt
      - BASE_PATH=/develop/
      - SERVER_URL=http://${COMPOSE_PROJECT_NAME}_client:3200/${COMPOSE_PROJECT_NAME}/alertaServer
      - GEOSERVER_URL=http://${COMPOSE_PROJECT_NAME}_geoserver:8080/${COMPOSE_PROJECT_NAME}/geoserver
    command: sh -c "/usr/share/nginx/html/develop/alerta/set-env.sh && nginx -g \"daemon off;\""
    hostname: satalertas_client
    volumes:
      - "satalertas_vol:/data"
    ports:
      - "${CLIENT_PORT}:80"
    networks:
      - frontend

  quickchart:
    image: ianw/quickchart
    restart: "always"
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 2
        condition: on-failure
    hostname: satalertas_quickchart
    ports:
      - "${QUICKCHART_PORT}:3400"
    networks:
      - backend

networks:
  backend:
    driver: overlay
    attachable: true

  frontend:
    driver: overlay
    attachable: true

configs:
  develop_satalertas_server_config:
    external: true
  develop_satalertas_geoserver_config:
    external: true

volumes:
  satalertas_documents_vol:
  satalertas_vol:
