version: "3.8"

services:

  server:
    image: ${TERRAMA2_DOCKER_REGISTRY}/${COMPOSE_PROJECT_NAME}-satalertas-server:${VERSION}
    restart: "always"
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 2
        condition: on-failure
    environment:
      - NODE_ENV=production
    volumes:
      - "satalertas_documents_vol:/app/documentos"
      - "satalertas_vol:/data"
    ports:
      - "${SERVER_PORT}:3200"
    networks:
      - backend
      - frontend

  client:
    image: ${TERRAMA2_DOCKER_REGISTRY}/${COMPOSE_PROJECT_NAME}-satalertas-client:${VERSION}
    restart: "always"
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 2
        condition: on-failure

    volumes:
      - "satalertas_vol:/data"
    ports:
      - "${CLIENT_PORT}:80"
    networks:
      - frontend

  quickchart:
    image: ianw/quickchart
    restart: "always"
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 2
        condition: on-failure
    ports:
      - "${QUICKCHART_PORT}:3400"
    networks:
      - backend

networks:
  backend:
    driver: overlay
    internal: true
    attachable: true

  frontend:
    driver: overlay
    internal: true
    attachable: true

volumes:
  satalertas_documents_vol:
  satalertas_vol:
