version: "3.8"

services:

  server:
    image: ${TERRAMA2_DOCKER_REGISTRY}/${COMPOSE_PROJECT_NAME}-satalertas-server:${VERSION}
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 2
        condition: on-failure
    hostname: satalertas_server
    environment:
      - NODE_ENV=production
    volumes:
      - "documents_vol:/app/documentos"
    ports:
      - "${SERVER_PORT}:3200"
    configs:
      - source: satalertas_server_config
        target: /app/config/config.json
    networks:
      - backend
      - frontend

  client:
    image: ${TERRAMA2_DOCKER_REGISTRY}/${COMPOSE_PROJECT_NAME}-satalertas-client:${VERSION}
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 2
        condition: on-failure
    environment:
      - PRODUCTION=true
      - PROJECT_ID=mpmt
      - BASE_PATH=/develop/
      - SERVER_URL=http://www.terrama2.dpi.inpe.br/${COMPOSE_PROJECT_NAME}/alertaServer
      - GEOSERVER_URL=http://www.terrama2.dpi.inpe.br/${COMPOSE_PROJECT_NAME}/geoserver
    command: sh -c "/usr/share/nginx/html/develop/alerta/set-env.sh && nginx -g \"daemon off;\""
    hostname: satalertas_client
    ports:
      - "${CLIENT_PORT}:80"
    networks:
      - frontend

  quickchart:
    image: ianw/quickchart
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 2
        condition: on-failure
    hostname: satalertas_quickchart
    ports:
      - "${QUICKCHART_PORT}:3400"
    networks:
      - backend

networks:
  backend:
    driver: overlay
    attachable: true

  frontend:
    driver: overlay
    attachable: true

configs:
  satalertas_server_config:
    external:
      name: "${COMPOSE_PROJECT_NAME}_satalertas_server_config"

volumes:
  documents_vol:
